environment:
  APP_SECRET: "${APP_SECRET}"
  DO_TOKEN: "${DO_TOKEN}"
packages:
    - name: dyn
      functions:
        - name: update4
          runtime: go:1.20
        - name: update6
          runtime: go:1.20